// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClou643q5M-ybepVL9wtBMyoX6FFY0h48',
    appId: '1:411023817970:web:b2baf13b4d0d244a70246b',
    messagingSenderId: '411023817970',
    projectId: 'cjet-80d45',
    authDomain: 'cjet-80d45.firebaseapp.com',
    storageBucket: 'cjet-80d45.appspot.com',
    measurementId: 'G-J6LVWDZL5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6IbFUXsrAmJYVDYEyLraak6DaxwOxoHA',
    appId: '1:411023817970:android:8feb77a2870b8c1770246b',
    messagingSenderId: '411023817970',
    projectId: 'cjet-80d45',
    storageBucket: 'cjet-80d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_lbictXQVhuMljjQxelGTbsRW1irRgk',
    appId: '1:411023817970:ios:2b168067a885be6970246b',
    messagingSenderId: '411023817970',
    projectId: 'cjet-80d45',
    storageBucket: 'cjet-80d45.appspot.com',
    iosClientId: '411023817970-rh9q80j2l4t72uspep0ckvmudq99pel0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy_lbictXQVhuMljjQxelGTbsRW1irRgk',
    appId: '1:411023817970:ios:41dc85304c7743b770246b',
    messagingSenderId: '411023817970',
    projectId: 'cjet-80d45',
    storageBucket: 'cjet-80d45.appspot.com',
    iosClientId: '411023817970-30tm54f7ctlbdp2ppbfrrqt2ej2vp1j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cjet.RunnerTests',
  );
}
